### ISSUE TITLE
Request for Code Availability

### ISSUE THREAD

**Issue by bring-nirachornkul** [markos-diomataris/wandr#1]
Congratulations on your excellent CVPR 2024 paper! Could you please provide the code? It would greatly assist us in our research and allow us to properly cite your work. Thank you!

**Comment by yunhanwang1105** [comment]
I'm also looking forward to the code.

**Comment by markos-diomataris** [comment]
Hi everyone, big thanks for your interest. I'm currently working on the code release. It will be out soon.
