### ISSUE TITLE
AssertionError: deps/statistics_amass_circle_smplx.npy stats file does not exist

### ISSUE THREAD

**Issue by eunjong55** [markos-diomataris/wandr#2]
Hello, 
Thank you for your great work.

I encountered an error while running the demo.py, which seems to be related to a missing file. Here are the details:

**Error Message:**
`AssertionError: deps/statistics_amass_circle_smplx.npy stats file does not exist
`

It looks like this file is not included in the repository. Could you please confirm if this is intentional or if the file is missing? If it is missing, could you provide guidance on how to obtain this file?

Any help in resolving this issue would be greatly appreciated.

Thank you.

**Comment by markos-diomataris** [comment]
Hi eunjong, thanks for trying my code. 

You are right, there was a problem with the .gitignore.
Try pulling again and let me know if it is fixed.

Cheers!

**Comment by eunjong55** [comment]
Thank you so much for your response and for addressing my question regarding the missing files. Your assistance is greatly appreciated.
